### ISSUE TITLE
ros2_example_bazel_installed: Should have simple cc,py example of using RMW isolation

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake-ros#115]
Per Anzu 9275, we should have a simple cc and py test that exercises RMW isolation.
e.g. `rmw_isolation_example_cc_test`, `rmw_isolation_example_py_test`

Both can simply publish a float, and do no other verification (for now).

They should then be referenced by:
https://github.com/RobotLocomotion/drake-ros/tree/eba927fd3ecf0ce2819200e0a8176e7d3f366e2a/bazel_ros2_rules/ros2#tools

What our extended usage looks like in Anzu:
https://gist.github.com/EricCousineau-TRI/bf120a42d7aa835037642789a4c3c985

\cc @IanTheEngineer

**Comment by adityapande-1995** [comment]
I see a test here for isolated listener and talker in both C++ and python : https://github.com/RobotLocomotion/drake-ros/blob/main/bazel_ros2_rules/ros2/resources/rmw_isolation/test/isolated_listener.py. To we require something more to resolve this issue ? cc @sloretz

**Comment by adityapande-1995** [comment]
Also a duplicate issue probably : https://github.com/RobotLocomotion/drake-ros/issues/77

**Comment by sloretz** [comment]
> Do we require something more to resolve this issue ? cc @sloretz

I think I recall this issue was to have an example test in the `ros2_example_bazel_installed` folder.

That folder is a separate bazel workspace, which matches what our downstream users would use. The C++/Python files will probably look similar, so IIUC the value in putting tests there is in showing what bazel rules to `load()` and run in the `WORKSPACE` and `BUILD.bazel` files.

**Comment by EricCousineau-TRI** [comment]
Yes, a very clear, user-based example of both C++ and Python of how to use isolation is my intent.

Having it in a more focused example workspace makes sense too! note that existing rmw_isolation tests are more for unittesting, less for exemplars.
