### ISSUE TITLE
Allow simulations to be restarted without restarting RViz

### ISSUE THREAD

**Issue by sloretz** [RobotLocomotion/drake-ros#144]
Right now the drake-ros systems use the Drake context as their source of time. RViz is unaware that simulated time is being used. 
This causes transform data from previous simulation runs because the "largest" time stamp is assumed to be the latest.

See this example where two simulation runs are done. The spheres on the second run are frozen at the place the previous simulation run ended at. When the second run catches up the spheres moves as expected.

[stopped_balls.webm](https://user-images.githubusercontent.com/4175662/191868703-898a3ad3-515b-4c4c-adf5-2af08c922ed2.webm)

RViz could be made aware of simulated time by creating a `/clock` topic publisher and launching RViz with `use_sim_time` enabled. More context and options are in this comment: https://github.com/RobotLocomotion/drake-ros/pull/133#pullrequestreview-1114531858

**Comment by EricCousineau-TRI** [comment]
\cc @IanTheEngineer
