### ISSUE TITLE
CMake Error: CMake server mode has been removed in favor of the file-api.

### ISSUE THREAD

**Issue by sloretz** [RobotLocomotion/drake-ros#149]
The [`bazel_ros2_rules` CMake scraping code uses the CMake server api](https://github.com/RobotLocomotion/drake-ros/blob/develop/bazel_ros2_rules/ros2/resources/cmake_tools/server_mode.py) - but it's been removed as of CMake 3.20. `bazel build //...` in `drake_ros_core` fails with a lot of the same message printed to the console:

```
CMake Error: CMake server mode has been removed in favor of the file-api.
```

@IanTheEngineer FYI this will need to be fixed to enable upgrading to Jammy.

**Comment by IanTheEngineer** [comment]
Resolved by #150 and #181.
