### ISSUE TITLE
Add BUILD.bazel files for drake_ros_viz and drake_ros_tf2

### ISSUE THREAD

**Issue by IanTheEngineer** [RobotLocomotion/drake-ros#158]
This will enable both drake-ros packages to be built in a bazel environment.

Note: When adding these package's BUILD.bazel files to drake-ros, inside the `cc_library` function, we should investigate using a recursive `glob` (and the `exclude` arg) to grab `src` files cleanly.

**Comment by sloretz** [comment]
Merged in #200 and #202. Closing as completed.
