### ISSUE TITLE
ROS 2: Improve the discovery methods used by nodes to prevent conflicts and accidental discoveries

### ISSUE THREAD

**Issue by gbiggs** [RobotLocomotion/drake-ros#183]
See [this Discourse thread](https://discourse.ros.org/t/proposed-changes-to-how-ros-performs-discovery-of-nodes/27640).

EDIT(eric): Removed text to minimize redundancy w.r.t. discourse post. Let's have as few sources of truth as possible!

**Comment by EricCousineau-TRI** [comment]
Thanks! Posted initial impression and requests here:
https://discourse.ros.org/t/proposed-changes-to-how-ros-performs-discovery-of-nodes/27640/17?u=ericcousineau-tri

**Comment by IanTheEngineer** [comment]
Agreed on removing the text from this ticket. However, it would be nice to see a meta-ticket on one of the relevant repositories that describes the different areas of improvement (preferably with check-boxes) to serve as a central point to link against when its eventually time to create PR's.

**Comment by EricCousineau-TRI** [comment]
Centralized issue: https://github.com/ros2/ros2/issues/1359

**Comment by mxgrey** [comment]
Note that there has been significant progress in making a testbed for the behaviors in this PR: https://github.com/osrf/iron_irwini_discovery_modes_prototype/pull/2

**Comment by mxgrey** [comment]
Relevant PRs:
* https://github.com/ros2/rmw/pull/349
* https://github.com/ros2/rcl/pull/1038
* https://github.com/ros2/rmw_fastrtps/pull/667
* https://github.com/ros2/rmw_cyclonedds/pull/441
* https://github.com/ros2/rmw_cyclonedds/pull/429
* https://github.com/ros2/rmw_connextdds/pull/108
* https://github.com/ros2/system_tests/pull/512

**Comment by EricCousineau-TRI** [comment]
Closed per our TRI SoW
