### ISSUE TITLE
ci: Should test transitioning towards official tarballs on Ubuntu Jammy

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake-ros#184]
From meeting notes, should ensure we have the following under CI to de-risk the infra work towards using Ubuntu Jammy:

- [ ] Jammy x Official Humble tarball
- [ ] Jammy x Official Rolling tarball
- Still needs determination on hosting resources
  - [ ] Jammy x Unofficial Humble tarball
  - [ ] Jammy x Unofficial Rolling tarball

@cottsay This is what I remember; please let me know if I missed anything.
\cc @IanTheEngineer

**Comment by cottsay** [comment]
The official publication will be enabled by ros2/ros_buildfarm_config#260.

**Comment by EricCousineau-TRI** [comment]
Scott to confirm/fix to ensure Focal CI has been removed.

**Comment by cottsay** [comment]
Everything looks good, closing this out.
