### ISSUE TITLE
installation instructions in drake_ros_examples/README.md doesn't obtain `colcon`?

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake-ros#230]
Unless I missed something. 

I had to manually install it following instructions from https://docs.ros.org/en/foxy/Tutorials/Beginner-Client-Libraries/Colcon-Tutorial.html

**Comment by adeeb10abbas** [comment]
I don't think you missed anything. I think the installation instructions don't include either `rosdep` or `colcon` it's just assumed the user would have it... although it would be very useful

**Comment by IanTheEngineer** [comment]
Thanks for opening this issue, Russ. The instructions for getting set up are in the `drake_ros_core` README and lean heavily on the ROS2 setup instructions:
https://github.com/RobotLocomotion/drake-ros/blob/main/drake_ros_core/README.md

That being said, I ran through the instructions, and the default ROS Humble / Rolling installation does not have the user installing `colcon` or `rosdep` for whatever reason. To me, that means our setup guide should  be more self contained. Simultaneously, we'll speak with folks to improve the upstream ROS2 setup docs.

**Comment by EricCousineau-TRI** [comment]
Thanks! We should address this after we land #205, just so we have a more cohesive and targeted location for concise, non-redundant instructions.

**Comment by EricCousineau-TRI** [comment]
I believe this should be resolved by #235. Let us know if it's still not clear.
