### ISSUE TITLE
[bazel] Should ensure pytest code is actually run or switch to `unittest`

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake-ros#243]
It's unclear to me if any `pytest`-based code is getting run via our Bazel setup.

My suggested options:
- Figure out how to have `pytest` run explicitly when `__name__ == "__main__"`
- Use `unittest` instead (my preference)

\cc @sloretz

**Comment by sloretz** [comment]
See https://github.com/EricCousineau-TRI/drake-ros/pull/6 which invokes pytest via

```python
if __name__ == '__main__':
    sys.exit(pytest.main(sys.argv))
```

> Use unittest instead (my preference)

One blocker is `ament_add_test` expects tests to output a junit xml file, which unittest doesn't do by default. Maybe this package would do it though? https://packages.ubuntu.com/jammy/python3-xmlrunner

**Comment by jwnimmer-tri** [comment]
Yup.  That's what [Drake uses](https://github.com/RobotLocomotion/drake/blob/v1.13.0/tools/workspace/xmlrunner_py/repository.bzl) for its python unit tests.

**Comment by EricCousineau-TRI** [comment]
Adding `pytest.main` works for me for now, and will resolve it.

FWIW, I don't love the "implicitness" of `pytest` (plugins, configuration, etc), and generally prefer `unittest`, if just for more clarity on what's happening. However, I don't want to sacrifice other work for this.

**Comment by EricCousineau-TRI** [comment]
I think this has been resolved-ish by ensuring we use the `pytest` ending stanza.
