### ISSUE TITLE
Use CMake file API in Bazel ROS build infrastructure

### ISSUE THREAD

**Issue by hidmic** [RobotLocomotion/drake-ros#29]
Starting with CMake 3.14, CMake introduced its file API to replace its CMake server mode, which was deprecated and later dropped in CMake 3.20. Because of this, the infrastructure introduced by #3 is not compatible with CMake 3.20 and onwards. 

We need to start using the CMake file API when the CMake server mode is missing.

**Comment by sloretz** [comment]
Done in #150. Closing as completed.
