### ISSUE TITLE
CI is broken due to rolling + Ubuntu 22.04 shift

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake-ros#41]
Currently, CI uses Docker images for rolling, and it's support (22.04) has shifted away from Drake's (20.04).

One possible solution is to use tarball approach to provision CI, even for non-Bazel workflows.

Drake Slack: https://drakedevelopers.slack.com/archives/C01B5B320QY/p1644958013772819

**Comment by sloretz** [comment]
I think this was resolved by #42, so I'll close it.
