### ISSUE TITLE
Define a Styleguide for drake-ros

### ISSUE THREAD

**Issue by IanTheEngineer** [RobotLocomotion/drake-ros#8]
- Consider the Drake's take on the Google Style Guide: 
  https://drake.mit.edu/code_style_tools.html
- Consider the ROS2's take on the Google Style Guide and Pep8:
  https://docs.ros.org/en/rolling/Contributing/Code-Style-Language-Versions.html
- Use `amelt_link_auto` tests to check for deviations from the chosen styleguide:
  https://github.com/ament/ament_lint/blob/master/ament_lint_auto/doc/index.rst

**Comment by hidmic** [comment]
It appears we've decided to follow Drake's path (based on #15). Shall we close this?

**Comment by EricCousineau-TRI** [comment]
I'd vote yes, with a note in a `README` pointing to the Drake URL Ian posted above.

**Comment by hidmic** [comment]
#30 is in, closing.
