### ISSUE TITLE
Add correct topology of frames to broadcast TF2 information

### ISSUE THREAD

**Issue by gbiggs** [RobotLocomotion/drake-ros#82]
The current implementation of `drake_ros_tf2` provides correct transforms for all frames in a system, but they are all rooted in the `world` frame. Although this does not have an impact on use of the frames via `tf2`, it does not align with how frames are usually presented in ROS, which is as a tree with each frame being rooted in its real-world parent (i.e. a kinematic chain).

The problem is compounded when there are multiple robots in a scene. It can become confusing to find the correct frame for a particular robot except by naming - which assumes that the names of the frames are suitable for identifying their topological order.

There are some possible ways to resolve this. One is to get the topology information from the Multibody Plant. Another is to modify Drake (and push this modification upstream in a PR) so that the Scene Graph knows about topology of the objects in the graph. (See `meshcat_visualizer.cc` in Drake.)

**Comment by sloretz** [comment]
Fixed by #91. Closing as completed.
